### ISSUE TITLE
Feature request: remove hardcoded keybindings in info messages

### ISSUE THREAD

**Issue by acid-bong** [djgoku/sops#3]
[This line on `sops-edit-file`](https://github.com/djgoku/sops/blob/main/sops.el#L119) uses hardcoded keybindings, which aren't necessary the end user's choice (I personally prefer `SPC c s ...` sequence). Instead it could get key bindings from the config (sadly I don't know how to implement this) or use function names

**Comment by djgoku** [comment]
Thank you for your issue. I am not sure how to do this either, but I'll look into fixing it.

**Comment by djgoku** [comment]
@acid-bong I hope v0.1.1 behavior is what you were expecting
